# Generated by Django 4.0.1 on 2022-05-01 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_farmimpliments_greenlandfarms_delete_farm_tool_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_mail', models.CharField(max_length=30)),
                ('customer_message', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.land')),
            ],
        ),
        migrations.CreateModel(
            name='FarmsPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=20)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_id', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.farmimpliments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
