# Generated by Django 4.0.1 on 2022-05-01 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_farmimpliments_greenlandfarms_delete_farm_tool_and_more'),
        ('users', '0002_useradress_landrequest_farmspayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmspayment',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.greenlandfarms'),
        ),
    ]
