# Generated by Django 4.0.1 on 2022-05-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_sharespayment_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmspayment',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='sharespayment',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
    ]
