# Generated by Django 4.0.1 on 2022-05-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_farmspayment_cost_alter_sharespayment_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
