# Generated by Django 4.0.1 on 2022-04-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_trending_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='quarter',
        ),
        migrations.AddField(
            model_name='trending',
            name='first_quarter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trending',
            name='second_quarter',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Quarter',
        ),
    ]
