# Generated by Django 4.0.1 on 2022-05-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_farmimpliments_greenlandfarms_delete_farm_tool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablejob',
            name='photo',
        ),
    ]
