# Generated by Django 4.0.1 on 2022-05-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=200000, max_digits=10),
            preserve_default=False,
        ),
    ]
