# Generated by Django 4.0.1 on 2022-05-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_shares_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='description',
            field=models.TextField(default='Buy Greenland shares with a minimum of $50 and get 80 - 100 return in a Year'),
        ),
        migrations.AddField(
            model_name='shares',
            name='max_cost',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shares',
            name='min_cost',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shares',
            name='offer_gain',
            field=models.TextField(default='Get up to so...so.percent return investing in so..so Shares'),
        ),
        migrations.AlterField(
            model_name='availablejob',
            name='description',
            field=models.TextField(default='I have a Job,(1) to do this...(2) to do that ...(...)'),
        ),
        migrations.AlterField(
            model_name='availableworker',
            name='description',
            field=models.TextField(default='I want to be a worker... i do this, i do that ... etc'),
        ),
        migrations.AlterField(
            model_name='shares',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
    ]
