# Generated by Django 4.0.1 on 2022-05-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_shares_date_added_shares_description_shares_max_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
